name: Susan Singer SCPM
favicon: null
layout_spectrum: 0.99724
typography_spectrum: 0.5448159018997103
title: Susan Singer SCPM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#b6bed3'
    - '#010101'
    - '#725ea5'
    - '#e26a4f'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
