name: Susan Singer SCPM
favicon: null
layout_spectrum: 0.86762
typography_spectrum: 0.5448159018997103
title: Susan Singer SCPM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#725ea5'
    - '#b0acc5'
    - '#e96f9e'
    - '#00916a'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
